WELCOME = 1
SELECT_EXPERIMENT = 2
PREVIOUS_THRESHOLD_CACHE = 3
THRESHOLD_CACHE = 4
PREVIOUS_SCORING = 5
SCORING = 6
PREVIOUS_WALDO_PROCESS = 7
WALDO_PROCESS = 8
FINAL = 9

SELECT_BATCHMODE_EXPERIMENTS = 10
BATCHMODE_THRESHOLD_CACHE = 11
