#!/usr/bin/env python
"""
Find all the collisions and visualize them to look at later
"""
from __future__ import print_function, absolute_import

# standard library
import sys
import argparse

# third party
import matplotlib.pyplot as plt

# project specific
import pathcustomize

import wio
import collider.viz.outlines as outlines

def main():
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument('experiment_id',
        help="Experiment ID to use.")

    args = parser.parse_args()
    eid = args.experiment_id

    experiment = wio.Experiment(experiment_id=eid)
    graph = experiment.graph

    gen = (bid for bid, deg in graph.in_degree_iter() if deg >= 2)
    print(','.join(['eid', 'bid', 'frame', 'filename']))
    for bid in gen:
        try:
            f, ax = outlines.show_collision(experiment, graph, bid)
            fn = '{}_{:05}.png'.format(eid, bid)
            f.savefig(fn)
            plt.close('all')
        except KeyError:
            #print("Failed to render result node {}".format(bid), file=sys.stderr)
            fn = ''

        print(','.join(str(x) for x in [eid, bid, int(experiment[bid].born_f), fn]))

if __name__ == '__main__':
    sys.exit(main())
