#!/usr/bin/env python
"""
rendercollisions

Takes all possible collision nodes (blobs with in-degree >1) and renders
them as a PNG, saving it to the present working directory. A CSV is written
to stdout containing the experiment ID, blob ID, frame, and file name.  Un-
parsable collisions will have a blank filename.

Example:
    ./rendercollisions 20130702_135652 | tee record.csv

Running the script in it's own empty folder is advisable as it will generate
a few thousand images.

    mkdir ../data/testset1
    cd ../data/testset1
    ../../scripts/rendercollisions 20130702_135652 | tee record.csv
"""
from __future__ import print_function, absolute_import

# standard library
import sys
import argparse

# third party
import matplotlib.pyplot as plt

# project specific
import pathcustomize

import wio
import collider
import collider.viz.outlines as outlines

def main():
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument('experiment_id',
        help="Experiment ID to use.")

    args = parser.parse_args()
    eid = args.experiment_id

    experiment = wio.Experiment(experiment_id=eid)
    graph = experiment.graph.copy()
    collider.remove_nodes_outside_roi(graph, experiment)

    gen = (bid for bid, deg in graph.in_degree_iter() if deg >= 2)
    print(','.join(['eid', 'bid', 'frame', 'filename']))
    for bid in gen:
        try:
            f, ax = outlines.show_collision(experiment, graph, bid)
            fn = '{}_{:05}.png'.format(eid, bid)
            f.savefig(fn)
            plt.close('all')
        except KeyError:
            #print("Failed to render result node {}".format(bid), file=sys.stderr)
            fn = ''

        print(','.join(str(x) for x in [eid, bid, int(experiment[bid].born_f), fn]))

if __name__ == '__main__':
    sys.exit(main())
