#!/usr/bin/env python
import pathcustomize

from waldo import wio
from waldo import report_card

def create_reports():
    ex_ids = [
        '20130318_131111',
        #'20130614_120518',
        #'20130702_135704',
    ]

    for ex_id in ex_ids:
        experiment = wio.Experiment(experiment_id=ex_id)
        graph = experiment.graph.copy()

        savename = '{eid}-report.csv'.format(eid=ex_id)
        graph2, report_df = report_card.collision_iteration2(experiment, graph)
        report_df.to_csv(savename)


if __name__ == '__main__':
    create_reports()
