#!/usr/bin/env python
import pathcustomize

from waldo import wio
from waldo import report_card

def create_reports():
    ex_ids = [
        '20141017_134720',
        '20141017_134724',
        '20130318_131111',
        '20130614_120518',
        '20130702_135704',
    ]

    # ex_ids = [ #'20141017_113435', '20141017_113439', '20141017_123722']
    #     '20141017_123725',
    #     '20141017_134720',
    #     '20141017_134724',
    #     '20141017_150959',
    #     '20141017_151002']
    # Note: 20141017_113439 causes an error
    # AssertionError: Edge from 101723 to 101723 is acausal, going back in time 150 frames

    # A6 plates. randomly chosen
    # 20130323_110247 20130323_170503 20130323_143707 20130323_132240 20130323_143706 20130324_130602

    ex_ids = ['20130323_110247', # moe
              '20130323_170503', # moe
              '20130323_143707', # larry
              '20130323_132240', # larry
              '20130323_143706', # curly
              '20130324_130602'] # curly


    for ex_id in ex_ids[-1:]:
        print ' ******* starting {eid}  *******'.format(eid= ex_id)
        ppath = '/home/visitors/peterwinter/codes/waldo/data/prep/{eid}'.format(eid=ex_id)
        wio.file_manager.ensure_dir_exists(ppath)
        experiment = wio.Experiment(experiment_id=ex_id)
        graph = experiment.graph.copy()

        savename = '{eid}-report.csv'.format(eid=ex_id)
        graph2, report_df = report_card.iterative_solver(experiment, graph)
        report_df.to_csv(savename)


if __name__ == '__main__':
    create_reports()
