#!/usr/bin/env python
import pathcustomize

import wio
import report_card

def create_reports():
    ex_ids = [
        #'20130318_131111',
        #'20130614_120518',
        #'20130614_120518',
        '20130702_135704',
    ]

    for ex_id in ex_ids:
        #try:
        experiment = wio.Experiment(experiment_id=ex_id, data_root=DATA_DIR)
        graph = experiment.graph.copy()

        savename = '{eid}-report.csv'.format(eid=ex_id)
        #graph1, df = create_report_card(experiment, graph.copy())
        #experiment, graph, report_df = main2(ex_id)
        graph2, report_df = report_card.collision_iteration2(experiment, graph)
        report_df.to_csv(savename)

        starts, ends = report_card.determine_lost_and_found_causes(experiment, graph2)

        starts_name = '{eid}-starts.csv'.format(eid=ex_id)
        df = report_card.summarize_loss_report(starts)
        df.to_csv(starts_name)

        ends_name = '{eid}-ends.csv'.format(eid=ex_id)
        df = report_card.summarize_loss_report(ends)
        df.to_csv(ends_name)
        #except Exception as e:
        #    print ex_id, 'failed due to:'
        #    print e


if __name__ == '__main__':
    create_reports()
    #experiment, graph, graph1 = main()
    #experiment, graph = main2()
    #determine_lost_and_found_causes(experiment, graph)

    #experiment = Experiment(experiment_id=ex_id, data_root=DATA_DIR)
    #graph = experiment.graph.copy()
    #collision_iteration2(experiment, graph)
    #collision_iteration(experiment, graph)
