#!/usr/bin/env python
import sys
import argparse
import pickle


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('graph_pickle', type=argparse.FileType('r'),
            help='Pickled NX graph')

    args = parser.parse_args()

    graph = pickle.load(args.graph_pickle)

    centroid_tracks = {}

    for node in graph:
        consolidate_node_data

        break

if __name__ == '__main__':
    sys.exit(main())
