#!/usr/bin/env python
import sys
import argparse
import pickle


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('timeline', type=argparse.FileType('r'),
            help='Processed timeline data')

    args = parser.parse_args()

    timeline = pickle.load(args.timeline)

if __name__ == '__main__':
    sys.exit(main())
