#!/usr/bin/env python
import sys
import argparse
import pickle

import networkx as nx

import pathcustomize
import wio

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('graph_pickle', type=argparse.FileType('r'),
            help='Pickled NX graph')

    args = parser.parse_args()

    graph = pickle.load(args.graph_pickle)

    print len(graph)

if __name__ == '__main__':
    sys.exit(main())
